// Writes packages/sdk/src/deployments.json (address + ABI per network) and packages/sdk/src/abi.ts.
//
//   tsx scripts/export-deployment.ts --abi-only
//   tsx scripts/export-deployment.ts --chain anvil|moderato [--rpc URL]
//
// Reads the ABI from contracts/out and the deployment from Foundry's broadcast file, then checks on
// the target RPC that the contract code exists and the deploy receipt succeeded before writing.
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { createPublicClient, getAddress, http, type Abi, type Address, type Hex } from 'viem'
import { chainArg, loadDotEnv, parseArgs, rpcFor } from './lib/args.ts'

const root = new URL('../', import.meta.url)
const artifactPath = new URL('contracts/out/FermataEscrow.sol/FermataEscrow.json', root)
const broadcastPath = new URL('contracts/broadcast/Deploy.s.sol/42431/run-latest.json', root)
const deploymentsPath = new URL('packages/sdk/src/deployments.json', root)
const abiTsPath = new URL('packages/sdk/src/abi.ts', root)

loadDotEnv()
const args = parseArgs()
const abi = JSON.parse(readFileSync(artifactPath, 'utf8')).abi as Abi

type Deployments = { FermataEscrow: { abi: Abi; networks: Record<string, unknown> } }
const current: Deployments = existsSync(deploymentsPath)
  ? JSON.parse(readFileSync(deploymentsPath, 'utf8'))
  : { FermataEscrow: { abi, networks: {} } }
current.FermataEscrow.abi = abi

if (!args['abi-only']) {
  const chain = chainArg(args)
  const rpc = rpcFor(chain, args)
  const run = JSON.parse(readFileSync(broadcastPath, 'utf8'))
  const tx = run.transactions.find((t: { contractName?: string; transactionType?: string }) =>
    t.contractName === 'FermataEscrow' && t.transactionType === 'CREATE')
  if (!tx) throw new Error('no FermataEscrow CREATE in the broadcast file')
  const address = getAddress(tx.contractAddress) as Address
  const hash = tx.hash as Hex
  const client = createPublicClient({ transport: http(rpc) })
  const [chainId, code, receipt] = await Promise.all([
    client.getChainId(),
    client.getCode({ address }),
    client.getTransactionReceipt({ hash }),
  ])
  if (!code || code === '0x') throw new Error(`no code at ${address} on ${rpc} (stale broadcast file?)`)
  if (receipt.status !== 'success') throw new Error(`deploy tx ${hash} did not succeed`)
  const read = (functionName: 'owner' | 'treasury' | 'feeBps') => client.readContract({ address, abi, functionName })
  const [owner, treasury, feeBps] = await Promise.all([read('owner'), read('treasury'), read('feeBps')])
  current.FermataEscrow.networks[chain] = {
    chainId,
    address,
    deployTx: hash,
    deployBlock: Number(receipt.blockNumber),
    deployGasUsed: Number(receipt.gasUsed),
    deployer: getAddress(receipt.from),
    owner,
    treasury,
    feeBps: Number(feeBps),
    deployedAt: new Date().toISOString(),
    ...(chain === 'moderato' ? { explorer: `https://explore.testnet.tempo.xyz/address/${address}` } : {}),
  }
  console.log(`FermataEscrow on ${chain}: ${address} (tx ${hash}, block ${receipt.blockNumber}, gas ${receipt.gasUsed})`)
}

writeFileSync(deploymentsPath, `${JSON.stringify(current, null, 2)}\n`)
writeFileSync(
  abiTsPath,
  `// Generated by scripts/export-deployment.ts from contracts/out/FermataEscrow.sol/FermataEscrow.json — do not edit.\n` +
    `export const fermataEscrowAbi = ${JSON.stringify(abi, null, 2)} as const\n`,
)
console.log(`wrote ${deploymentsPath.pathname} and ${abiTsPath.pathname}`)
